// <auto-generated />
namespace Trakk.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class userprofileimages : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(userprofileimages));
        
        string IMigrationMetadata.Id
        {
            get { return "201704242333217_user-profile-images"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
