// <auto-generated />
namespace API.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class teamfixturesetups : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(teamfixturesetups));
        
        string IMigrationMetadata.Id
        {
            get { return "201704212300145_team-fixture-setups"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
